astra_db:
  collection_name: "filieris-rag"

embedding_model:
  provider: "huggingface"
  model_name: "BAAI/bge-m3"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "deepseek-r1-distill-llama-70b" 

chroma:
  persist_directory: "notebook/all_data2"

retriever:
  top_k: 15